# Generated by Django 5.2.14 on 2026-05-20 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointment_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.CharField(max_length=20, verbose_name='Ώρα'),
        ),
    ]
